### ISSUE TITLE
EUMETSAT - Bad rendering with preparedStatements

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#192] opened 2019-12-13 16:13 UTC
See https://osgeo-org.atlassian.net/browse/GEOS-9433 to reproduce

Found on: PostgreSQL 9.6.12 + Postgis 2.5.2

**Comment by imranrajjad** [comment] 2020-02-04 09:29
Things verified so far:

- [ ] Data is being Fetched
- [ ] The final SQL filter is correct
- [ ] Check Rendering Pipeline
- [ ] Try with another simple data set and see same issue occurs

**Comment by simboss** [comment] 2020-02-04 10:15
@imranrajjad investigation make take a couple of hours not more.

Then report where you are.

**Comment by imranrajjad** [comment] 2020-02-04 13:59
### Investigation results

So after some tiring 5 hours of  debugging, the issues is caused due to difference in byte arrays of return ed representing the stored WKB geometry

#### WIthout Prepared Statement (working)

- Geometry column qualifier : encode(ST_AsTWKB(ST_Simplify(ST_Force2D("the_geom"), 0.00439453125, true),3), 'base64')
- Byte Array : [-95, 0, -17, -35, -88, 11, -64, -9, 103]
- Hex String : A100EFDDA80BC0F767


#### WIth Prepared Statement (broken)

- Geometry column qualifier : ST_AsBinary("the_geom")
- Byte Array : [1, 1, 0, 0, 0, 0, 0, 0, 0, -119, -85, 93, -64, 0, 0, 0, -128, 74, 7, 33, 64]
- Hex String : 01010000000000000089AB5DC0000000804A072140

Plugging this Hex String on http://kostas.krevatas.net/wkt-wkb-geojson-convert-online/ shows the correct geometry `POINT(-118.68023681640625 8.514240264892578)` , instead it is parsed as `POINT(0,0)` and hence the map goes empty

### Root Cause
As it can be seen both byte arrays differ completely in size. This change in size causes the function at [VarintDataInStream.readSignedInt](https://github.com/geotools/geotools/blob/master/modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/VarintDataInStream.java#L91) to always return a 0.

#### Re-producing in Unit test
This has been further verified by plugging Hex string in the test [TWKBReaderTest.testPointGeometries](https://github.com/geotools/geotools/blob/master/modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/TWKBReaderTest.java#L45)

 where

` checkTWKBGeometry("01010000000000000089AB5DC0000000804A072140", "POINT(-118.68023681640625 8.514240264892578)");`

fails assertion with following error 

```
junit.framework.AssertionFailedError: 
Expected:POINT (-118.68023681640625 8.514240264892578)
Actual:  POINT (0 0)
```

### Suggested fix

Make the VarintDataInStream tolerable to the longer byte array
Use same select qualifier for both prepared and non-prepared statement

**Comment by aaime** [comment] 2020-02-04 14:02
@imranrajjad you probably need to read the TWKB spec and figure out if there is a simple bug in how it is parsed

**Comment by imranrajjad** [comment] 2020-02-04 14:04
@aaime  thanks for hint,
Are these the specs to follow?

**Comment by nmco** [comment] 2020-02-04 15:11
@imranrajjad note that each function returns a different binary format:
* [ST_AsTWKB](https://postgis.net/docs/ST_AsTWKB.html), _Returns the geometry in TWKB (Tiny Well-Known Binary) format. TWKB is a compressed binary format with a focus on minimizing the size of the output_.  
* [ST_AsBinary](https://postgis.net/docs/ST_AsBinary.html), _Returns the Well-Known Binary representation of the geometry. There are 2 variants of the function. The first variant takes no endian encoding parameter and defaults to server machine endian. The second variant takes a second argument denoting the encoding - using little-endian ('NDR') or big-endian ('XDR') encoding._

Open question from me, (maybe you know @aaime) any specific reason for using a different encoding for geometries when using prepared statements? Because if not then I guess we could use the same for both :rescue_worker_helmet:.

**Comment by aaime** [comment] 2020-02-04 15:56
@nmco having enough time you could change both, trying to get things out quickly on an un-unfunded task, not :-D

**Comment by imranrajjad** [comment] 2020-02-05 05:27
so apparently the closest fix is to use the correct qualifier in select statement fetching geometry using ST_AsTWKB. please let me know if this is acceptable and I have a go ahead

**Comment by aaime** [comment] 2020-02-05 09:39
@imranrajjad the direction is good but I believe your proposal is a bit too simplistic.

The dialects in JDBCDataStore are stateless, which causes issues when we are dynamically deciding whether to use TWKB or not, which depends on the configuration, the hints passed, and the data at hand... the part that encodes the geometry needs to agree with the part that decodes it, but they are not allowed to keep state in between.

So what's going on here... in PostGISDialect (used for non PS path) the encoding of the geometry column in select is [delegated to the GeometryColumnEncoder](https://github.com/geotools/geotools/blob/c9e275e7d78b3f0ba58cd89f6c4cb9a46c69b648/modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java#L381), which applies some complex logic to decide if to use WKB or TWKB (the latter is always simplifying, so it makes sense to use only if there is a simplification distance, and cannot be used for arcs).
The [reading part then applies some logic to decide if TWKB has been used](https://github.com/geotools/geotools/blob/c9e275e7d78b3f0ba58cd89f6c4cb9a46c69b648/modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java#L316
), and does the decoding accordingly.

The prepared dialect, PosgisPSDialect, delegates to the non prepared one to setup the select portion of the query and does the same for reading... but it seems something is lost along the way, as it's not working all the time... but it happens only for points, and I'm not sure why.
Suggestion: put a breakpoint [here in JDBCDataStore](https://github.com/geotools/geotools/blob/bae4ea158dd39cf766f7ead19c93a81222a4cce5/modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java#L4880) and see how the geometry encoding is happening... I'm guessing that for some reason, and for points only, the code ends up encoding a request using WKB but then assumes the read has to be done with TWKB.

Again, as said, there is no "use TWKB for everything" since it can't be used in a variety of situations.

**Comment by nmco** [comment] 2020-02-05 10:02
Great feedback @aaime, thank you! @imranrajjad looks like you have a plan to update.

**Comment by imranrajjad** [comment] 2020-02-05 13:52
@aaime thanks for the feedback and direction. Another detailed debugging session reveled that indeed there was a mismatch cause by a missing delegate call to a method canSimplifyPoints() in PostGISDialect from PostGISPSDialect. This was causing the select qualifier to request WKB instead of TWKB. 

 ```
@Override
    public boolean canSimplifyPoints() {
        return delegate.canSimplifyPoints();
    }
```


This is a subtle change and will require a Prepared statment version of [PostgisSimplifiedGeometryTest](https://github.com/geotools/geotools/blob/f7dfcd843b7d5d1481ba2623ae4a10b839a67072/modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisSimplifiedGeometryTest) Unit test class

Estimate : 1 hour

**Comment by nmco** [comment] 2020-02-05 18:23
Bear in mind @Imran that test for this will be an online (the test you reference is an online test), hence requiring a PostgreSQL instance. If your estimate already had this into account, then looks good to me :+1:.

**Comment by imranrajjad** [comment] 2020-02-06 06:01
JIRA : https://osgeo-org.atlassian.net/browse/GEOT-6511
PR : https://github.com/geotools/geotools/pull/2797

**Comment by nmco** [comment] 2020-02-06 10:47
Merged on master, waiting for the backport to 22.x and @imranrajjad is checking if 22.x is affected, report here when investigated.

**Comment by imranrajjad** [comment] 2020-02-06 16:44
21.x is not effected

22.x backport PR : https://github.com/geotools/geotools/pull/2798

**Comment by Gnafu** [comment] 2020-02-10 09:57
I see this is a GeoTools only fix.
Will I get this for free if I just rebuild this? https://github.com/geosolutions-it/geoserver/tree/EOWS-158 

Or is there any change to be made on the EOWS.158 GeoServer branch as well?

**Comment by imranrajjad** [comment] 2020-02-10 10:13
@Gnafu what GT version is this branch using? The backport is yet to be done for 22.x GT branch.

**Comment by Gnafu** [comment] 2020-02-10 10:37
22-SNAPSHOT (rev 149c8707868da0f356b5d484e7418f0fd175e2f2)
Since it is a snapshot I guess I'll get the fix once the PR is merged and a build is done.
Correct?

**Comment by imranrajjad** [comment] 2020-02-10 10:43
(drum rolls)


that's correct 🌟

**Comment by nmco** [comment] 2020-02-10 11:49
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOT-6511

Merged in 23.x and 22.x, this translates to 2.17.x and 2.16.x respectively.

**Closed by nmco** 2020-02-10 11:49 UTC
Labels: Priority: Low, bug
