### ISSUE TITLE
NPE if a Jiffle Rendering Transformation is used with Channel Selection

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#134] opened 2018-12-06 18:37 UTC
See [GEOS-9048](https://osgeo-org.atlassian.net/browse/GEOS-9048)

**Comment by aaime** [comment] 2018-12-21 16:52
Found where the issue is, it's related to band selection optimization in direct rendering path, which should not be activated with rendering transforms (since the band selection must occur on the output of the RT, not its input). Still weirded out that this was not happening on master, and yet I've not found significant code differences between the two branches on the classes that handle the jiffle process, renderedimagemapoutputformat, streamingrenderer, or gridcoveragerenderer. To be evaluated.

**Comment by aaime** [comment] 2018-12-21 16:59
Self note: test plan is to adapt the jiffle script to a RBG image and then use it as a RT in GetMapIntegrationTest, making sure it does not go "boom"

**Comment by simboss** [comment] 2019-01-09 09:34
@aaime don't forget to backport to 2.14

**Comment by aaime** [comment] 2019-01-09 13:58
Backport done. Assigning to @Gnafu for tests

**Closed** 2020-04-10 09:07 UTC
Labels: In Test, Priority: High, bug
