### ISSUE TITLE
GeoServer Importer uses wrong datastore 

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#327] opened 2020-04-10 09:25 UTC
If 2 datastores in different workspaces have the same name, GeoServer uses always the first it finds.

I am unable to reproduce this bug locally because of another bug: https://osgeo-org.atlassian.net/browse/GEOS-9571

The steps to reproduce are the same, just trigger the import after them.
The importer adds the 2.tif file to the index of the datastore "a:m" instead of the specified "b:m"

I believe this is due to this line here: 
https://github.com/geoserver/geoserver/blob/cd81e50877a51d1ac5c1c9d84165cc3364477dde/src/extension/importer/rest/src/main/java/org/geoserver/importer/rest/ImportController.java#L200-L204

The datastore is looked up by name, ignoring the workspace, so the first one that gets found, gets used.

**Comment by taba90** [comment] 2020-04-14 10:04
This got reproduced. The issue is caused by the line highlighted by @Gnafu . fix + test one hour

**Comment by nmco** [comment] 2020-04-14 13:00
Go ahead @taba90 :small_airplane:.

**Comment by taba90** [comment] 2020-04-15 06:48
Master pull request https://github.com/geoserver/geoserver/pull/4187

**Comment by taba90** [comment] 2020-05-07 10:34
Master merged.
Backport prs:
2.17.x https://github.com/geoserver/geoserver/pull/4230
2.16.x https://github.com/geoserver/geoserver/pull/4229
Fix as been backported as well to the client branch

**Comment by randomorder** [comment] 2020-09-01 09:12
I can see the commits on the fork
![image](https://user-images.githubusercontent.com/5264230/91831093-ea888180-ec43-11ea-98d3-6af37c2b3e22.png)

I deployed yesterday. We just need to test it before closing the issue

**Closed** 2020-10-01 17:30 UTC
Labels: Priority: High, backport-required, bug, geoserver
