### ISSUE TITLE
Limit GeoServer Importer parallelism

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/eumetsat-EOWS#72] opened 2018-03-19 11:04 UTC
GeoServer can run MAX_INT number of jobs concurrently, without any configurable limit.

See https://osgeo-org.atlassian.net/browse/GEOS-8648

**Comment by simboss** [comment] 2018-04-17 07:45
duplicate of #69

**Closed** 2018-04-17 07:45 UTC
Labels: backlog, enhancement
